### ISSUE TITLE
Build successful but I don't see any artifacts available to download in github.

### ISSUE THREAD

**Issue by itzteajay-glitch** [jtdor/build-deb-action#12]
So I'm just diving into this world of building my own packages for some of my automations. I managed to get it to push out a successful build but for whatever reason I cannot download the artifacts coming out of the build. I guess my question would be is the exporting of artifacts in scope for this action? Or is the expectation to point the artifacts to a specific place so then another action could pick them up and release them? 

![Screenshot from 2024-09-01 17-56-30](https://github.com/user-attachments/assets/8742de8c-47b4-4ae9-ae5d-1a37a3670b0c)

**Comment by bocan** [comment]
You've got to upload the artifacts with another action.  Add a step like this:

```
        name: upload
        uses: actions/upload-artifact@v4
        with:
          path: debian/artifacts/
          name: debian_package
```
