### ISSUE TITLE
Documentation improvement: suggestion

### ISSUE THREAD

**Issue by colisee** [jtdor/build-deb-action#6]
Hi, 

the documentation does not mention how to generate source and binary (which is the default behavior for dpkg-buildpackage)

This is the github action code I used in that respect:
```
jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      -
        name: build-deb-amd64
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=full
          extra-build-deps: pristine-tar git
          before-build-hook: pristine-tar checkout ../$(pristine-tar list)
          host-arch: amd64
      -
        name: upload
        uses: actions/upload-artifact@v3
        with:
          path: debian/artifacts/
          name: debian_package
```

Note:
- I assume the repository to be checked out has a `pristine-tar` branch that contains the upstream tarball delta
- I check out all branches of the repository with the argument `fetch-depth: 0`
- I install additional packages with `extra-build-deps: pristine-tar git`
- I specify the argument `buildpackage-opts: --build=full`

Feel free to add the above to your documentation, if you feel it could be of use.

Cheers.
